# Archive for every catering document that has legal or bookkeeping value:
#
#   offers/<requestId>/v<NNNN>.pdf      - each offer version the owner sent
#   signed/<requestId>/v<NNNN>.pdf      - the PAdES-sealed agreement returned
#                                         by the BankID signing provider
#   invoices/<stripeInvoiceId>.pdf      - copy of every finalized Stripe
#                                         invoice/receipt and credit note
#
# Stripe hosts invoices too, but Bokföringslagen makes the restaurant - not
# Stripe - responsible for keeping räkenskapsinformation for 7 years, so a
# copy lands here. The hash of each object is stored on the request record
# (and in catering-request-history), so any later tampering is detectable.
#
# Nothing here is public. Customers and owners download through short-lived
# presigned GET URLs generated by catering-customer / catering-offer.

# S3 bucket names are globally unique across every AWS account, not just
# this one - the account ID suffix guarantees no collision without needing
# a manually-chosen unique name per account.
data "aws_caller_identity" "current" {}

locals {
  is_prod = var.environment == "prod"
}

resource "aws_s3_bucket" "catering_documents" {
  bucket = local.is_prod ? "catering-documents-${data.aws_caller_identity.current.account_id}" : "${var.environment}-catering-documents-${data.aws_caller_identity.current.account_id}"

  # Object Lock is switched on at creation. It can't be switched off again,
  # and versioning (below) can never be suspended once it's on.
  object_lock_enabled = true

  # Dev only: lets the environment be torn down. Dev objects are in
  # GOVERNANCE mode (below), which the destroy can bypass. Prod stays
  # false - and COMPLIANCE-mode objects couldn't be deleted early anyway.
  force_destroy = !local.is_prod

  tags = {
    Environment = var.environment
  }
}

resource "aws_s3_bucket_versioning" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Default retention applied to every new object version.
#
#   prod: COMPLIANCE, 7 years - nobody, not even the account root user, can
#         delete or overwrite a version before it expires. That's the point:
#         the signed agreement and invoices are evidence.
#   dev:  GOVERNANCE, 1 day - same code paths exercised, but test data can
#         still be cleaned up (s3:BypassGovernanceRetention) and the bucket
#         destroyed.
resource "aws_s3_bucket_object_lock_configuration" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  rule {
    default_retention {
      mode  = local.is_prod ? "COMPLIANCE" : "GOVERNANCE"
      years = local.is_prod ? 7 : null
      days  = local.is_prod ? null : 1
    }
  }

  depends_on = [aws_s3_bucket_versioning.catering_documents]
}

resource "aws_s3_bucket_public_access_block" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

# SSE-S3 rather than a customer-managed KMS key: no extra key policy for
# every Lambda role (and presigned URLs) to carry, and Object Lock is what
# protects these documents, not key access.
resource "aws_s3_bucket_server_side_encryption_configuration" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Documents are read a lot in the first weeks (customer downloads, owner
# looks them up) and almost never after a year - Glacier Instant Retrieval
# keeps them millisecond-readable at a fraction of the storage price.
resource "aws_s3_bucket_lifecycle_configuration" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  rule {
    id     = "archive-after-one-year"
    status = "Enabled"

    filter {}

    transition {
      days          = 365
      storage_class = "GLACIER_IR"
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.catering_documents]
}

resource "aws_s3_bucket_policy" "catering_documents" {
  bucket = aws_s3_bucket.catering_documents.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "DenyInsecureTransport"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.catering_documents.arn,
          "${aws_s3_bucket.catering_documents.arn}/*",
        ]
        Condition = {
          Bool = { "aws:SecureTransport" = "false" }
        }
      }
    ]
  })

  depends_on = [aws_s3_bucket_public_access_block.catering_documents]
}
